{
 "title": "MDB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mchines",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(mdb_machine_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Types",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (type)(mdb_machine_types)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burndown",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mdb_machine_types{type=\"MACHINE_TYPE_UNKNOWN\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}