name: Create production promotion pull request
on:
  push:

permissions:
  pull-requests: write

jobs:
 pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0
      - name: pull-request
        run: |
          gh pr create --fill-first
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}%   